In [10]:
!pip install -U scikit-learn==1.9.0

Collecting scikit-learn==1.9.0
  Downloading scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.9.0) (2.0.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.9.0) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.9.0) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.9.0) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.9.0) (3.6.0)
Downloading scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 81.8 MB/s eta 0:00:00
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
Successfully installed scikit-learn-1.9.0

In [1]:
import sklearn
print(sklearn.__version__)

1.9.0

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [4]:
import pandas as pd

df = pd.read_csv("news.csv")

print("Rows and Columns:", df.shape)
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Rows and Columns: (45757, 2)
Number of Rows: 45757
Number of Columns: 2

In [5]:
df = pd.read_csv("news.csv",engine="python",on_bad_lines='skip')
df.head()

                                                text  label
0  Gere faults Trump for blurring meaning of 'ref...      1
1  German parties start to find common ground in ...      1
2  Senate Democratic leader says Attorney General...      1
3  Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4   Trump Threw Mar-A-Lago Fundraiser For Woman A...      0

In [6]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45757 entries, 0 to 45756
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    45757 non-null  object
 1   label   45757 non-null  int64
dtypes: int64(1), object(1)
memory usage: 715.1+ KB

text     0
label    0
dtype: int64

In [7]:
df = df.dropna()

In [8]:
print(df.shape)
df.info()
print(df.isnull().sum())
print(df['label'].value_counts())

(45757, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45757 entries, 0 to 45756
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    45757 non-null  object
 1   label   45757 non-null  int64
dtypes: int64(1), object(1)
memory usage: 715.1+ KB
text     0
label    0
dtype: int64
label
1    22900
0    22857
Name: count, dtype: int64

In [12]:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["label"] = le.fit_transform(df['label'])

In [13]:
X = df.drop("label",axis=1)
y = df["label"]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [16]:
print(X_train.shape)
print(y_train.shape)

(1, 1)
(36605,)

In [17]:
print(df.columns)

Index(['text', 'label'], dtype='object')

In [18]:
print(df.columns)
df.head()

Index(['text', 'label'], dtype='object')

                                                text  label
0  Gere faults Trump for blurring meaning of 'ref...      1
1  German parties start to find common ground in ...      1
2  Senate Democratic leader says Attorney General...      1
3  Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4   Trump Threw Mar-A-Lago Fundraiser For Woman A...      0

In [19]:
print(X_train.shape)
print(y_train.shape)

(1, 1)
(36605,)

In [20]:
type(X_train)

scipy.sparse._csr.csr_matrix

In [21]:
X = df['text']
y = df['label']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english')

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

print(X_train.shape)
print(y_train.shape)

(36605, 143236)
(36605,)

In [22]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [23]:
y_pred = model.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9742132867132867

In [25]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97      4606
           1       0.98      0.97      0.97      4546

    accuracy                           0.97      9152
   macro avg       0.97      0.97      0.97      9152
weighted avg       0.97      0.97      0.97      9152

In [26]:
news = ["Scientists discover a new method to generate clean energy"]

news_vector = vectorizer.transform(news)

prediction = model.predict(news_vector)

if prediction[0] == 1:
    print("Fake News")
else:
    print("Real News")

Real News

In [27]:
import joblib

joblib.dump(model, "fake_news_model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

['vectorizer.pkl']

In [28]:
from google.colab import files

files.download("fake_news_model.pkl")
files.download("vectorizer.pkl")