<a href="https://colab.research.google.com/github/Annamdevula1/Fake-News-Detector-For-Students/blob/main/FAKE_NEWS_DETECTOR_PROJECT_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [4]:
df = pd.read_csv("news.csv",on_bad_lines='skip')
df.head()

                                                text  label
0  Gere faults Trump for blurring meaning of 'ref...      1
1  German parties start to find common ground in ...      1
2  Senate Democratic leader says Attorney General...      1
3  Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4   Trump Threw Mar-A-Lago Fundraiser For Woman A...      0

In [5]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45757 entries, 0 to 45756
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    45757 non-null  object
 1   label   45757 non-null  int64
dtypes: int64(1), object(1)
memory usage: 715.1+ KB

text     0
label    0
dtype: int64

In [6]:
df = df.dropna()

In [7]:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["label"] = le.fit_transform(df['label'])

In [8]:
X = df.drop("label",axis=1)
y = df["label"]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [11]:
print(X_train.shape)
print(y_train.shape)

(1, 1)
(36605,)

In [12]:
print(df.columns)

Index(['text', 'label'], dtype='object')

In [13]:
print(df.columns)
df.head()

Index(['text', 'label'], dtype='object')

                                                text  label
0  Gere faults Trump for blurring meaning of 'ref...      1
1  German parties start to find common ground in ...      1
2  Senate Democratic leader says Attorney General...      1
3  Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4   Trump Threw Mar-A-Lago Fundraiser For Woman A...      0

In [14]:
print(X_train.shape)
print(y_train.shape)

(1, 1)
(36605,)

In [15]:
type(X_train)

scipy.sparse._csr.csr_matrix

In [16]:
X = df['text']
y = df['label']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english')

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

print(X_train.shape)
print(y_train.shape)

(36605, 143236)
(36605,)

In [17]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [18]:
y_pred = model.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9742132867132867

In [20]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97      4606
           1       0.98      0.97      0.97      4546

    accuracy                           0.97      9152
   macro avg       0.97      0.97      0.97      9152
weighted avg       0.97      0.97      0.97      9152

In [21]:
news = ["Scientists discover a new method to generate clean energy"]

news_vector = vectorizer.transform(news)

prediction = model.predict(news_vector)

if prediction[0] == 1:
    print("Fake News")
else:
    print("Real News")

Real News

In [22]:
import joblib

joblib.dump(model, "fake_news_model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

['vectorizer.pkl']

In [23]:
from google.colab import files

files.download("fake_news_model.pkl")
files.download("vectorizer.pkl")